import { useReveal } from '../hooks/useReveal';

export function Privacy() {
  useReveal();

  return (
    <section className="legal-page">
      <div className="legal-container">
        <h1>Privacy Policy</h1>
        <p className="last-updated">Last updated: June 21, 2026</p>
        
        <p>This Privacy Policy describes how SIA "Soccer Bridge USA" ("We," "Us," "Our," or the "Company") collects, uses, shares, and protects personal data when You use our website and services.</p>
        <p>By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>Words with capitalized initial letters have meanings defined under the following conditions. These definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
        
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li><strong>Company</strong> ("We," "Us," or "Our") refers to SIA "Soccer Bridge USA", a company registered in the Republic of Latvia, registration No. [registration number], registered address Miera iela 87a, Riga, Latvia.</li>
          <li><strong>Country</strong> refers to Latvia.</li>
          <li><strong>Personal Data</strong> means any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the website, accessible from www.usasoccerbridge.com.</li>
          <li><strong>Service Provider</strong> means any third party that processes data on Our behalf in order to operate the Service or provide services to Us.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, generated by use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or, in the case of a minor, the parent or legal guardian providing consent on their behalf.</li>
        </ul>

        <h2>The Personal Data We Collect</h2>
        <h3>Information You Provide to Us</h3>
        <p>When You fill out an application or contact form, submit materials, or otherwise communicate with Us, We may collect:</p>
        <ul>
          <li>Contact details, such as first name, last name, email address, and phone number;</li>
          <li>Player information, such as graduation year ("Class of"), club or team name, position, and playing level;</li>
          <li>Academic information, such as GPA, transcripts, academic records, and standardized test scores;</li>
          <li>Athletic information, such as highlight videos, statistics, and biographical or athletic profile information;</li>
          <li>Any message or other information You choose to include when contacting Us; and</li>
          <li>If You purchase a service, billing and payment details, which are processed via Our payment provider.</li>
        </ul>

        <h3>Information Collected Automatically</h3>
        <p>When You visit the Service, We may automatically collect certain Usage Data, such as Your device's IP address, browser type and version, the pages of the Service You visit, the time and date of Your visit, and other diagnostic data. We may collect this data using cookies or similar technologies (see "Cookies and Tracking Technologies" below).</p>

        <h2>How We Use Your Personal Data</h2>
        <p>We use the Personal Data We collect for the following purposes:</p>
        <ul>
          <li>To provide and manage Our recruitment support services, including creating Your player profile;</li>
          <li>To share Your player profile, academic records, highlight videos, and related information with college coaches, athletic programs, and educational institutions, in order to pursue scholarship and recruitment opportunities on Your behalf;</li>
          <li>To communicate with You about Your application, Our services, and any updates relevant to You;</li>
          <li>To process payments for any services You purchase; and</li>
          <li>To maintain, improve, and ensure the security of Our website and services.</li>
        </ul>

        <h2>Legal Basis for Processing (EU/EEA Users)</h2>
        <p>If You are located in the European Economic Area, We process Your Personal Data on the following legal bases:</p>
        <ul>
          <li><strong>Consent:</strong> where You have given Us consent to process Your Personal Data for one or more specific purposes, such as sharing Your profile with coaches and institutions;</li>
          <li><strong>Performance of a contract:</strong> where processing is necessary to provide the services You have requested, including transferring Your Personal Data to recipients outside the EEA as described below;</li>
          <li><strong>Legitimate interests:</strong> where processing is necessary for Our legitimate interests, such as maintaining the security of Our Service, provided those interests are not overridden by Your data protection rights; and</li>
          <li><strong>Legal obligation:</strong> where processing is necessary for Us to comply with the law, for example accounting and tax record-keeping.</li>
        </ul>

        <h2>Sharing and Disclosure of Your Personal Data</h2>
        <h3>College Coaches, Athletic Programs, and Educational Institutions</h3>
        <p>The core purpose of Our Service is to share Your player profile, academic records, highlight videos, and related information with coaches and staff at colleges and universities affiliated with the NCAA, NAIA, and NJCAA, in order to help You pursue athletic scholarship and recruitment opportunities. We share this information based on Your request and consent when You engage Our services.</p>
        
        <h3>Service Providers</h3>
        <p>We use third-party tools and Service Providers to help Us operate, including for email communication, client and contact management (CRM), video hosting and editing, website hosting, and payment processing. These Service Providers only process Personal Data on Our instructions and are required to keep it confidential and secure.</p>
        
        <h3>Legal Requirements</h3>
        <p>We may disclose Your Personal Data if required to do so by law, or in response to valid requests by public authorities (for example, a court or government agency).</p>

        <h2>International Data Transfers</h2>
        <p>Because Our Service connects You with educational institutions and athletic programs located in the United States, Your Personal Data (including Your player profile, academic records, and highlight videos) will be transferred to, and processed in, the United States and potentially other countries outside the European Economic Area.</p>
        <p>This transfer is a core part of the service You have requested, and is carried out at Your request and with Your consent, for the purpose of pursuing recruitment and scholarship opportunities on Your behalf. Where We use Service Providers located outside the EEA for other purposes (for example, hosting or email services), We will take reasonable steps to ensure Your Personal Data continues to receive an appropriate level of protection, including through contractual safeguards where applicable.</p>

        <h2>Children's Privacy</h2>
        <p>Our Service is intended for use by prospective student-athletes together with their parents or legal guardians. If You are under 18 years of age, Your use of the Service, and Our collection and use of Your Personal Data, requires the knowledge and consent of a parent or legal guardian.</p>
        <p>We do not knowingly collect Personal Data from children without such consent. If You are a parent or legal guardian and believe Your child has provided Us with Personal Data without Your consent, please contact Us using the details below so We can address this.</p>

        <h2>Data Retention</h2>
        <p>We retain Your Personal Data for as long as is necessary to provide Our services to You, including for the duration of the recruitment process and a reasonable period afterward in case You wish to resume the process or have follow-up questions (typically up to 24 months after Our last contact with You).</p>
        <p>We may retain certain information for longer where required by law, for example accounting and tax records. When We no longer need Your Personal Data, We will delete it or take steps to anonymize it.</p>

        <h2>Cookies and Tracking Technologies</h2>
        <p>We may use cookies and similar tracking technologies to operate and improve the Service, for example to remember Your preferences or understand how visitors use Our website. You can instruct Your browser to refuse all cookies or to indicate when a cookie is being sent. If You do not accept cookies, some features of the Service may not function as intended.</p>

        <h2>Data Security</h2>
        <p>We use reasonable organizational and technical measures designed to protect Your Personal Data from accidental loss, unauthorized access, alteration, or disclosure. However, no method of transmission over the internet or electronic storage is completely secure, and We cannot guarantee absolute security.</p>

        <h2>Your Rights</h2>
        <p>If You are located in the European Economic Area, You have the following rights regarding Your Personal Data, subject to applicable law:</p>
        <ul>
          <li><strong>Right to access:</strong> to request a copy of the Personal Data We hold about You;</li>
          <li><strong>Right to rectification:</strong> to request correction of inaccurate or incomplete Personal Data;</li>
          <li><strong>Right to erasure:</strong> to request deletion of Your Personal Data, subject to certain exceptions (for example, where We must retain data to comply with a legal obligation);</li>
          <li><strong>Right to restriction of processing:</strong> to request that We limit how We use Your Personal Data in certain circumstances;</li>
          <li><strong>Right to data portability:</strong> to receive a copy of certain Personal Data in a structured, commonly used format;</li>
          <li><strong>Right to object:</strong> to object to Our processing of Your Personal Data where We rely on legitimate interests; and</li>
          <li><strong>Right to withdraw consent:</strong> where We rely on Your consent, to withdraw it at any time, without affecting the lawfulness of processing carried out before withdrawal.</li>
        </ul>
        <p>To exercise any of these rights, please contact Us using the details below. We may ask You to verify Your identity before responding to Your request.</p>

        <h2>Links to Other Websites</h2>
        <p>Our Service may contain links to other websites that are not operated by Us, including websites of educational institutions and athletic programs. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the privacy policy of any website You visit, as We have no control over, and assume no responsibility for, the content or privacy practices of any third-party sites.</p>

        <h2>Changes to This Privacy Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will notify You of any material changes by updating the "Last updated" date at the top of this Privacy Policy and, where appropriate, by other means such as posting a notice on Our Service.</p>

        <h2>Contact Us</h2>
        <p>If You have any questions about this Privacy Policy, or wish to exercise any of Your rights regarding Your Personal Data, You can contact Us:</p>
        <ul>
          <li>By email: info@soccerbridgeusa.com</li>
        </ul>
      </div>
    </section>
  );
}
